server.port=1001
spring.datasource.url=jdbc:mysql://localhost:3306/fruit
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.thymeleaf.cache=false

spring.application.name=Fruit Shop

